---
- debug: msg="Dropping database {{ database.name }}"
  run_once: true

- name: Drop database
  run_once: true
  shell: >
    docker exec {{ container_id }} mongosh
    --quiet
    --eval '
      if (db.getMongo().getDBNames().includes("{{ database.name }}"))
      {
        db = db.getSiblingDB("{{ database.name }}");
        db.dropDatabase();
        db.dropDatabase()
      }'
  register: drop_database
  changed_when: drop_database.stdout | length > 0

- debug:
    msg:
      - "Container ID: {{ container_id }}"
      - "Status: {{ (drop_database.stdout | length > 0) | \
        ternary(drop_database.stdout, 'Database ' ~ database.name ~ ' does not exist') }}"
  run_once: true
