---
- hosts: client_hosts
  remote_user: vagrant
  gather_facts: no

  vars:
    image: ycsb:latest
    workload: workloada
    record_count: 10000
    threads: 4
    target: 0
    output_file: /dev/null

  tasks:
    - name: Assert arguments
      assert:
        that:
          - image | trim | length > 0
          - workload | trim | length > 0
          - record_count | int > 0
          - threads | int > 0
          - target | int >= 0
          - output_file | trim | length > 0

    - name: Get IP address of {{ groups['server_hosts'][0] }}
      shell: getent hosts {{ groups['server_hosts'][0] }} | awk '{print $1}'
      register: connection_addr
      delegate_to: manager
      changed_when: false

    - set_fact:
        connection_addr: "{{ connection_addr.stdout }}:{{ database.connection.port_no }}"

    - name: Run container
      shell: >
        docker run
        --rm
        {{ image }} load mongodb -s
        -P workloads/{{ workload }}
        -p mongodb.url=mongodb://{{ connection_addr }}/{{ database.name }}?w=1
        -p recordcount={{ record_count }}
        -threads {{ threads }}
        -target {{ target }}
        -p exporter=site.ycsb.measurements.exporter.JSONArrayMeasurementsExporter
        -p exportfile={{ output_file }}
      register: run_result

    - debug: msg="{{ run_result.cmd }}"
    - debug: msg="{{ run_result.stderr_lines }}"
