---
- hosts: managed
  remote_user: vagrant
  gather_facts: yes

  vars:
    system: "{{ ansible_facts['system'] }}"
    machine: "{{ ansible_facts['machine'] }}"
    dest: "/usr/local/bin/docker-compose"

  tasks:
    - debug: msg="system={{ system }}, machine={{ machine }}"

    - name: Download and install docker-compose binary
      become: yes
      become_method: sudo
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/\
          docker-compose-{{ system }}-{{ machine }}"
        dest: "{{ dest }}"
        mode: "0775"
        force: yes
      notify:
        - Get version
        - Print version

  handlers:
    - name: Get version
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Print version
      debug: msg="Installed {{ docker_compose_version.stdout }}"
