---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  tasks:
    - name: ensure ntp is at the latest version
      apt: pkg=ntp state=latest
      notify: restart ntp
  handlers:
    - name: restart ntp
      service: name=ntp state=restarted
