---
- hosts: manager
  remote_user: vagrant
  gather_facts: no

  tasks:
    - shell: uname -a
      register: uname_result
    - debug: msg="{{ uname_result.stdout }}"
    - name: copy temporary inventory
      copy:
        src: "{{ inventory_file }}"
        dest: /home/vagrant/provisioning/inventory.ini
        owner: vagrant
        group: vagrant
        mode: '0644'
