---
- hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  vars:
    cleanup: true
    force_regen: false

  tasks:
    - import_tasks: tasks/server/cluster/stack-assert.yaml

    - import_tasks: tasks/server/cluster/remove-stack.yaml
      when: cleanup
      notify: Cleanup artifacts

    - meta: flush_handlers

    - name: Check if {{ deployment.compose_file }} exists
      stat:
        path: "{{ deployment.compose_file }}"
      register: compose_file_stat

    - fail:
        msg: File {{ deployment.compose_file }} must be a regular file
      when: compose_file_stat.stat.exists and not compose_file_stat.stat.isreg

    - include_tasks: tasks/server/cluster/generate-compose-file.yaml
      when: not compose_file_stat.stat.exists or force_regen
      vars:
        dbserver_count: 2
        coordinator_count: 1

    - name: Deploy stack
      command: >-
        docker stack deploy --compose-file {{ deployment.compose_file }} {{ stack.name }}
      register: stack_deploy_result

    - debug: msg={{ stack_deploy_result.stdout_lines }}

  handlers:
    - name: Cleanup artifacts
      include_tasks: tasks/server/cluster/cleanup.yaml
