---
- hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  tasks:
    - import_tasks: tasks/stack-assert.yaml

    - import_tasks: tasks/server-sharded-remove.yaml
      notify: Cleanup artifacts

  handlers:
    - name: Cleanup artifacts
      include_tasks: tasks/server-sharded-cleanup.yaml
