---
- hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  vars:
    remove_volumes: true

  tasks:
    - import_tasks: tasks/server/single/exists.yaml

    - name: Stop container
      when: container_id | length
      shell: docker stop {{ container.name }}

    - name: Remove volumes
      shell: docker volume rm --force {{ container.data_vol }} {{ container.config_vol }}
      when:
        - container_id | length
        - remove_volumes

    - name: Create container {{ container.name }}
      shell: >
        docker container run
        --rm
        --cpus {{ resources.single.limit.cpu }}
        --name {{ container.name }}
        --mount type=volume,src={{ container.data_vol }},target=/data/db
        --mount type=volume,src={{ container.config_vol }},target=/data/configdb
        --publish {{ database.connection.port_no }}:27017
        --detach
        {{ container.image }}
