---
- name: Drop database
  hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  tasks:
    - import_tasks: tasks/server/single/exists.yaml
      notify:
        - Drop database

    # Must to set this fact since both drop-db.yaml and exists.yaml use container_id
    - set_fact:
        container_id: "{{ container_id.stdout }}"

  handlers:
    - name: Drop database
      include_tasks: tasks/server/common/drop-db.yaml
