---
- hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  tasks:
    - import_tasks: tasks/server/cluster/generate-compose-file.yaml
      vars:
        dbserver_count: 2
        coordinator_count: 1
