---
- hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  vars:
    remove_volumes: true

  tasks:
    - import_tasks: tasks/server/single/exists.yaml

    - name: Stop container
      when: container_id | length
      shell: docker stop {{ container.name }}

    - name: Remove volumes
      shell: docker volume rm --force {{ container.data_vol }} {{ container.config_vol }}
      when:
        - container_id | length
        - remove_volumes
