---
- name: Query collection properties
  hosts: servers
  remote_user: vagrant
  gather_facts: no

  tasks:
    - import_tasks: tasks/server/cluster/get-latest-coordinator.yaml

    - include_tasks: tasks/server/common/query-col-props.yaml
      when: container_ls | length
      vars:
        container_id: "{{ container_ls }}"

    - fail:
        msg: "No coordinators found, is the cluster running?"
      when: collection_properties is not defined
