---
- name: Provision database servers
  hosts: server_hosts
  remote_user: vagrant
  gather_facts: no

  tasks:
    - name: Get list of containers with label {{ stack.label.repl_set }}
      shell: >
        docker container ls
        --quiet
        --no-trunc
        --filter label={{ stack.label.repl_set }}
        --filter label={{ stack.namespace }}
      delegate_to: "{{ item }}"
      run_once: true
      loop: "{{ groups['servers'] }}"
      register: containers_repl_set
      changed_when:
        - containers_repl_set.stdout_lines | length > 0
      notify: Provision replica sets

    - debug:
        msg:
          server: "{{ item.item }}"
          containers: "{{ item.stdout_lines }}"
      loop: "{{ containers_repl_set.results }}"
      loop_control:
        index_var: idx
        label: "{{ idx }}"

    - name: Flush handlers
      meta: flush_handlers

  handlers:
    - name: Provision replica sets
      include_tasks: tasks/provision/replica-set.yaml
      when:
        - result_item.stdout_lines | length > 0
      loop: "{{ containers_repl_set.results }}"
      loop_control:
        loop_var: result_item
        label: "{{ result_item.item }}"
      vars:
        container:
          hostname: "{{ result_item.item }}"
          ids: "{{ result_item.stdout_lines }}"
