---
ycsb:
  image: ycsb:latest
  service: ycsb-service
  label: lsse.project.client.ycsb_artifact

arangobench:
  image: arangobench:latest
  service: arangobench-service
  label: lsse.project.client.arangobench_artifact
