---
- name: Check if container {{ container.name }} exists
  shell: docker container ls --no-trunc --quiet --filter name=^/{{ container.name }}$
  register: container_id
  changed_when: false

- set_fact:
    container_id: "{{ container_id.stdout }}"
