---
- name: Join a docker swarm
  hosts: "{{ pb_workers }}"
  remote_user: vagrant

  vars:
    swarm_info: "{{ pb_swarm_info }}"

  tasks:
    - name: Join swarm command
      shell: >
        docker swarm join --token
        {{ swarm_info.token }} {{ swarm_info.addr }}:{{ swarm_info.port }}
      register: swarm_join_result

    - debug: msg="{{ swarm_join_result.stdout }}"
